server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri: mongodb://xcmedia:xcmedia@192.168.56.1:27017
      database: xc_media
  #rabbitmq配置
  rabbitmq:
    host: 192.168.56.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: ${MEDIA_FILE_LOCATION:/Users/atom/video/}
  ffmpeg-path: /usr/local/bin/ffmpeg