server:
  port: 22100
spring:
  application:
    name: xc-service-base-filesystem
  #mongo配置
  data:
    mongodb:
      uri: mongodb://xcfs:xcfs@192.168.56.1:27017
      database: xc_fs
  #SpringMVC上传文件配置
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 1MB
      # 最大支持请求大小
      max-request-size: 30MB


# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: #缩略图生成参数
    width: 150
    height: 150
  tracker-list: #TrackerList参数,支持多个
    - 192.168.56.200:22122